### ISSUE TITLE
Add endpoint to get a specific song

### ISSUE THREAD

**Issue by BjoernPetersen** [BjoernPetersen/MusicBot-API#15]
`/provider/{providerId}/song/{songId}`

**Comment by FelixGail** [comment]
How does this differ to the already included `/provider/{providerId}/{songId}`? 

https://github.com/BjoernPetersen/MusicBot-API/blob/31ab34830d96b0ea880ff95d60ebb51498164ce7/MusicBot.yaml#L393-L425

**Comment by BjoernPetersen** [comment]
Based on the creation time of this issue, I guess I just "overlooked" that operation.
