### ISSUE TITLE
Add permissions enum

### ISSUE THREAD

**Issue by IIIuminator** [BjoernPetersen/MusicBot-API#8]
For reliable deserialization of JSON payloads containing permissions, JWT claims and pre-api call auth checks a list of possible permissions would be useful

**Comment by BjoernPetersen** [comment]
Have a look at [Permission.kt](https://github.com/BjoernPetersen/MusicBot/blob/develop/src/main/kotlin/net/bjoernpetersen/musicbot/api/auth/Permission.kt), which is currently the only place those permissions are defined.
